http://192.168.4.1/

###

GET http://192.168.4.1/user

###

GET http://192.168.4.1/user?name=cab

###

GET http://192.168.4.1/user/1145

###

POST http://192.168.4.1/user/1149?name=teste

###

PUT http://192.168.4.1/user/1358?name=joselito marombado

###

DELETE http://192.168.4.1/user/1358

###

OPTIONS http://192.168.4.1/user

